version: "3" 
services:
  app:
    image: golang:1.9
    ports:
      - "5000:5000"
    tty: true
    working_dir: /src
    volumes:
      - .:/src
    environment:
      # MYSQL_USER: dena
      # MYSQL_PASSWORD: dena 
      MYSQL_DATABASE: test
      ISUBATA_DB_HOST: mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      # MYSQL_ROOT_PASSWORD: root 
      # MYSQL_USER: dena
      # MYSQL_PASSWORD: dena 
      MYSQL_DATABASE: isubata
  nginx:
    ports:
      - "80:80"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/:/src/public/
